---
# tasks file for nutanix_role_prism_flow_adv_net
- include_tasks: setup_api.yml

- name: "Task can only be run against Prism Central"
  ansible.builtin.fail:
    msg: "'nutanix_host' needs to be set to the IP or VIP of Prism Central. Please check the nutanix_host variable and try again."
  when:
    - nutanix_endpoint_prism_type != 'pc'

- name: Check Flow Advanced Networking Pre-Reqs
  include_tasks: check_prereqs.yml

- name: Enable Flow Advanced Networking
  include_tasks: enable_adv_net.yml
  when:
    - enable_flow_adv_net
